src/main/java/spharos/msg/domain/cart/controller/CartController.java
src/main/java/spharos/msg/domain/cart/service/CartService.java

Cart 컨트롤러, 서비스에 시큐리티 관련 코드가 남아 있어서 삭제 했습니다.
버그 수정이라 급하게 pr올렸습니다 죄송합니다
Resolves: #9
어떤 변경 사항이 있나요?

fix: 시큐리티 관련 코드 삭제

---

src/main/java/spharos/msg/MsgApplication.java
src/main/java/spharos/msg/domain/likes/service/LikesService.java
src/main/java/spharos/msg/global/api/ApiResponse.java

Api 응답에 isSuccess 프로퍼티 추가 구현했습니다.또한 ApiResponse와 관련된 부분을 일부 수정했는데, 이부분은 나중에 꼭 담당자 분이 SuccessStatus로 옮겨주세요!
어떤 변경 사항이 있나요?

feat : api 응답에 isSuccess 프로퍼티 추가 구현 #19

---

src/main/java/spharos/msg/domain/users/entity/Users.java

feat : Users 테이블 양방향 Mapping 추가 및 Colum 추가

---

src/main/java/spharos/msg/domain/cart/controller/CartProductController.java
src/main/java/spharos/msg/domain/cart/dto/CartProductResponseDto.java
src/main/java/spharos/msg/domain/cart/service/CartProductService.java
src/main/java/spharos/msg/domain/likes/controller/LikesController.java
src/main/java/spharos/msg/domain/likes/service/LikesService.java
src/main/java/spharos/msg/global/api/code/status/ErrorStatus.java
src/main/java/spharos/msg/global/api/code/status/SuccessStatus.java
src/main/java/spharos/msg/global/api/exception/ProductNotExistException.java

좋아요 기능에서 응답값을 SuccessStatus로 통일 했습니다.
Resolves: #28  
어떤 변경 사항이 있나요?

fix : 좋아요 기능 응답 값 통일

---

src/main/java/spharos/msg/domain/cart/controller/CartProductController.java
src/main/java/spharos/msg/domain/cart/dto/CartProductResponseDto.java
src/main/java/spharos/msg/domain/cart/service/CartProductService.java
src/main/java/spharos/msg/domain/likes/controller/LikesController.java
src/main/java/spharos/msg/domain/likes/service/LikesService.java

좋아요/장바구니 기능에서 유저 정보를 조회할 때 UserDetails를 통해 조회하도록 수정했습니다.
Resolves: #24 
어떤 변경 사항이 있나요?

fix : 좋아요/장바구니 유저 조회 수단 변경

---

src/main/java/spharos/msg/domain/cart/controller/CartProductController.java
src/main/java/spharos/msg/domain/coupon/controller/CouponController.java
src/main/java/spharos/msg/domain/coupon/dto/CouponResponseDto.java
src/main/java/spharos/msg/domain/coupon/entity/Coupon.java
src/main/java/spharos/msg/domain/coupon/repository/CouponRepository.java
src/main/java/spharos/msg/domain/coupon/scheduler/CouponScheduler.java
src/main/java/spharos/msg/domain/coupon/service/CouponService.java
src/main/java/spharos/msg/domain/users/entity/UserCoupon.java
src/main/java/spharos/msg/domain/users/repository/UsersCouponRepository.java
src/main/java/spharos/msg/global/api/ApiResponse.java
src/main/java/spharos/msg/global/api/code/status/ErrorStatus.java
src/main/java/spharos/msg/global/api/code/status/SuccessStatus.java

- 다운 가능한 쿠폰 조회
- 쿠폰 다운로드
- 보유중인 쿠폰 조회
- 기한 만료시 스케줄러를 통한 삭제
Resolves: #31 
어떤 변경 사항이 있나요?

feat : 쿠폰 조회/다운/삭제

---

.gitignore
src/main/java/spharos/msg/global/config/SwaggerConfig.java

login으로 발급된 jwt 토큰을 통해 한번 인증을 하면 더이상 jwt 토큰 인증을 할 필요 없도록 편의성을 더했습니다.
추후 자세한 것은 trouble shooting에 적어두겠습니다.
어떤 변경 사항이 있나요?

feat : swagger 테스트용 JWT 토큰 발급 기능 추가 #42

---

.github/workflows/buildWithTest.yml
src/main/java/spharos/msg/domain/users/entity/Address.java
src/main/java/spharos/msg/domain/users/repository/AddressRepository.java
src/test/java/spharos/msg/MsgApplicationTests.java

빌드 시 이제 테스트코드가 실행됩니다.
이제 테스트 통과 못하면 PR 및 merge가 안됩니다!
어떤 변경 사항이 있나요?

ci : TestCode 검사용 GitAction 추가 #35

---

src/main/java/spharos/msg/domain/users/controller/UsersController.java
src/main/java/spharos/msg/domain/users/dto/NewAddressRequestDto.java
src/main/java/spharos/msg/domain/users/entity/Users.java
src/main/java/spharos/msg/domain/users/service/AddressService.java
src/main/java/spharos/msg/domain/users/service/UsersService.java
src/main/java/spharos/msg/global/api/code/status/SuccessStatus.java
src/main/java/spharos/msg/global/api/example/ExampleController.java

1. 로그아웃  API 추가 되었습니다.
2. Users <-> Address 양방향 매핑 시, Data 저장 안되는 문제 해결하였습니다.
어떤 변경 사항이 있나요?

feat : 유저 로그아웃 구현 및 버그 수정

---

src/main/java/spharos/msg/domain/cart/controller/CartProductController.java
src/main/java/spharos/msg/domain/cart/dto/CartProductCheckDto.java
src/main/java/spharos/msg/domain/cart/entity/CartProduct.java
src/main/java/spharos/msg/domain/cart/service/CartProductService.java
src/main/java/spharos/msg/domain/cart/service/CartProductUpdateService.java
src/main/java/spharos/msg/domain/users/repository/AddressRepository.java
src/main/java/spharos/msg/global/api/code/status/ErrorStatus.java

프론트에서 사용할 때 각각 따로 필요할 것 같다고 해서 기존 하나였던 장바구니 수정 API를 개별로 분리했습니다.
Resolves: #44 
어떤 변경 사항이 있나요?

refactor : 장바구니 수정 API 분리

---

src/main/java/spharos/msg/domain/users/controller/TokenController.java
src/main/java/spharos/msg/global/api/code/status/ErrorStatus.java
src/main/java/spharos/msg/global/security/JwtAuthenticationFilter.java
src/main/java/spharos/msg/global/security/JwtTokenProvider.java

#53 
Controller 호출 후, Header 에서 Authorization 값으로 Token을 받아오는 경우, Uuid를 추출할때 사용합니다.
1. JwtTokenProvider를 의존성 주입 합니다.
2. getUuid({token}) 호출합니다.
※ 단, Bearer 추가 되어있는 토큰이 입력되어야 정상 작동합니다.
Success : return uuid
fail : thow JwtTokenException
+ 추가) 매직넘버로 -> 상수화 진행
어떤 변경 사항이 있나요?

feat : JwtTokenProvider 토큰 검증 로직에 대한 수정

---

src/main/java/spharos/msg/domain/users/entity/Users.java

#71 
기존 getUsername = uuid 호출 하게 되어있어 문제 발생.
readUserName() 메소드 호출 시, username 정상 출력 되로록 메소드 추가 진행
어떤 변경 사항이 있나요?

feat : User Entity userName 반환 메소드 추가

---

src/main/java/spharos/msg/domain/cart/controller/CartProductController.java
src/main/java/spharos/msg/domain/cart/entity/CartProduct.java
src/main/java/spharos/msg/domain/cart/service/CartProductService.java
src/main/java/spharos/msg/domain/cart/service/CartProductUpdateService.java
src/main/java/spharos/msg/global/entity/BaseEntity.java

- 데이터의 무결성을 위해 엔티티에서 수정하던 방식에서 새로 빌드하는 방식으로 변경
- 불필요한 유저 검증 과정 제거
#68 
어떤 변경 사항이 있나요?

fix : 장바구니 수정 방식 변경

---

src/main/resources/application.yml
src/test/java/spharos/msg/domain/users/service/UsersServiceTest.java

fix : JPA Redis Repository scan 문제 해결

---

src/main/java/spharos/msg/domain/search/controller/SearchController.java
src/main/java/spharos/msg/domain/search/dto/SearchResponse.java
src/main/java/spharos/msg/domain/search/repository/SearchRepository.java
src/main/java/spharos/msg/domain/search/repository/SearchRepositoryImpl.java
src/main/java/spharos/msg/domain/search/service/SearchService.java
src/main/java/spharos/msg/domain/search/utils/SearchKeywordFinder.java
src/main/java/spharos/msg/global/api/code/BaseErrorCode.java
src/main/java/spharos/msg/global/api/code/status/ErrorStatus.java
src/main/java/spharos/msg/global/api/exception/ExceptionAdvice.java
src/main/java/spharos/msg/global/api/exception/SearchException.java
src/test/java/spharos/msg/domain/search/service/SearchServiceTest.java

#94에 대한 모든 구현 사항을 완료했습니다.
추가적인 테스트까지 마쳤습니다.
어떤 변경 사항이 있나요?

refactor : 검색 결과 조회 API 코드 리팩토링 및 검색 예외 처리 강화 #94

---

src/main/java/spharos/msg/domain/admin/controller/CountPriceController.java
src/main/java/spharos/msg/domain/admin/controller/CountUserController.java
src/main/java/spharos/msg/domain/admin/entity/CountPrice.java
src/main/java/spharos/msg/domain/admin/entity/CountUser.java
src/main/java/spharos/msg/domain/admin/repository/CountPriceRepository.java
src/main/java/spharos/msg/domain/admin/repository/CountUserRepository.java
src/main/java/spharos/msg/domain/admin/service/CountPriceService.java
src/main/java/spharos/msg/domain/admin/service/CountUserService.java

#92 
Admin용 Table ERD와 동일하게 작성하였습니다.
수정사항 있으시면 말씀 부탁드립니다!
어떤 변경 사항이 있나요?

feat : Admin 집계용 Table 생성

---

src/main/java/spharos/msg/MsgApplication.java
src/main/java/spharos/msg/domain/users/controller/AuthController.java
src/main/java/spharos/msg/domain/users/dto/response/FindUserInfoOutDto.java
src/main/java/spharos/msg/domain/users/service/AuthService.java
src/main/java/spharos/msg/domain/users/service/AuthServiceImpl.java
src/main/java/spharos/msg/global/api/code/status/ErrorStatus.java
src/main/java/spharos/msg/global/api/code/status/SuccessStatus.java

#98 
My Page용 회원 정보 조회 Api 추가 합니다.
현재, userName만 반환하게 되어있으나, 요구사항에 따라 데이터 추가가 있을 듯 하여, 확장성 있게 개발해두었습니다.
어떤 변경 사항이 있나요?

feat : MyPage용 회원 정보 조회 API

---

src/main/java/spharos/msg/domain/category/controller/CategoryController.java
src/main/java/spharos/msg/domain/category/dto/CategoryResponse.java
src/main/java/spharos/msg/domain/category/repository/CategoryProductRepositoryCustom.java
src/main/java/spharos/msg/domain/category/repository/impl/CategoryProductRepositoryCustomImpl.java
src/main/java/spharos/msg/domain/category/service/CategoryService.java
src/test/java/spharos/msg/domain/category/repository/CategoryProductRepositoryTest.java

대카테고리 외에는 parent_id,parent_name을 보내지 않도록 했습니다.
어떤 변경 사항이 있나요?

want : 카테고리 목록 조회 API의 응답값 변경 및 반환값에 parent_id 추가 #128

---

src/main/java/spharos/msg/domain/likes/controller/LikesController.java
src/main/java/spharos/msg/domain/likes/dto/IsLikesDto.java
src/main/java/spharos/msg/domain/likes/dto/LikesResponseDto.java
src/main/java/spharos/msg/domain/likes/service/LikesService.java

개별 상품의 좋아요 유무를 조회하는 api 입니다.
#135 
어떤 변경 사항이 있나요?

Feature : 개별 상품 좋아요 유무 조회 #135

---

src/main/java/spharos/msg/domain/options/controller/OptionsController.java
src/main/java/spharos/msg/domain/options/dto/OptionsNameDto.java
src/main/java/spharos/msg/domain/options/dto/OptionsResponseDto.java
src/main/java/spharos/msg/domain/options/service/OptionsService.java

product_option_id를 쿼리파람으로 받아서 옵션을 조회합니다
#142 
어떤 변경 사항이 있나요?

feat : 개별 상품 옵션 조회 #142

---

src/main/java/spharos/msg/domain/admin/controller/CountUserController.java
src/main/java/spharos/msg/domain/admin/dto/AdminResponseDto.java
src/main/java/spharos/msg/domain/admin/service/CountUserService.java
src/main/java/spharos/msg/domain/users/entity/LoginType.java
src/main/java/spharos/msg/domain/users/repository/UsersRepository.java
src/main/java/spharos/msg/global/api/code/status/SuccessStatus.java

#104 
전체 탈퇴한 회원 수 API
월별 가입자 수 API
두개 마무리 하여 추가하였습니다.
월별 가입자 수 Service로직이 너무 가독성이 안좋아 보이고 어려워 보입니다...
혹시 좋은 방법이 있으면 추천 부탁드립니다.
현재) 오늘기준으로 작년도 1월부터 createdAt 비교하여 모든 사용자 가져와서 데이터 분할 후 전달.
어떤 변경 사항이 있나요?

feat : Admin용 사용자 Api 추가

---

.idea/dataSources.xml
src/main/java/spharos/msg/domain/product/controller/ProductController.java
src/main/java/spharos/msg/domain/product/dto/ProductResponse.java
src/main/java/spharos/msg/domain/product/repository/ProductRepository.java
src/main/java/spharos/msg/domain/product/service/ProductService.java

베스트탭 상품 내려주는 api 구현하였습니다.
productList 필드에 상품id가 담긴 배열을 내려주고,
isLast필드로 마지막 페이지인지 아닌지 알려주도록 구현하였습니다.
어떤 변경 사항이 있나요?

feat: 베스트탭의 상품 목록 조회 api 구현

---

.idea/dataSources.xml
src/main/java/spharos/msg/MsgApplication.java
src/main/java/spharos/msg/domain/product/dto/ProductResponse.java
src/main/java/spharos/msg/domain/product/service/ProductService.java
src/main/resources/application.yml

상품 상세 조회 api 반환값에 responseTime 추가
ddl-auto:none으로 변경하여 다시 pr합니다. 주의할게요..!
어떤 변경 사항이 있나요?

feat: 상품 상세 조회 api 반환값에 responseTime 추가

---

src/main/java/spharos/msg/domain/search/controller/SearchController.java
src/main/java/spharos/msg/domain/search/dto/SearchResponse.java
src/main/java/spharos/msg/domain/search/repository/SearchRepository.java
src/main/java/spharos/msg/domain/search/repository/SearchRepositoryImpl.java
src/main/java/spharos/msg/domain/search/service/SearchService.java
src/test/java/spharos/msg/domain/search/service/SearchServiceTest.java

실시간 상품 검색어가 누락되던 문제를 해결했습니다.
더불어서 코드를 좀 더 리팩토링 했습니다.
테스트 코드 또한 추가했습니다!
어떤 변경 사항이 있나요?

bug : 실시간 상품 검색 API 검색어 누락 문제 #152

---

.idea/dataSources.xml
src/main/java/spharos/msg/domain/product/controller/ProductController.java
src/main/java/spharos/msg/domain/product/dto/ProductResponse.java
src/main/java/spharos/msg/domain/product/repository/ProductRepository.java
src/main/java/spharos/msg/domain/product/service/ProductService.java
src/main/java/spharos/msg/global/api/code/status/SuccessStatus.java

admin 페이지 베스트 11 반환 api 구현하였습니다.
productSellTotalCount 필드를 기준으로 내림차순하여 모든 상품을 불러온후, limit메서드로 11개 까지만 dto로 변환하였습니다!
어떤 변경 사항이 있나요?

feat: admin 페이지 베스트 11 반환 api 구현

---

.idea/dataSources.xml
src/main/java/spharos/msg/MsgApplication.java
src/main/java/spharos/msg/domain/product/controller/ProductController.java
src/main/java/spharos/msg/domain/product/service/ProductService.java

ADMIN용 상품 조회 API에 두 가지 수정사항 반영하였습니다.
- 프론트 쪽에서 배열을 문자열로 넘기기로 하여서, 대괄호를 제거한 후 배열로 변환하는 것으로 수정
- responseTime 추가
어떤 변경 사항이 있나요?

feat: ADMIN용 상품 조회 API 추가 개발

---

src/main/java/spharos/msg/domain/product/dto/ProductResponse.java
src/main/java/spharos/msg/domain/product/service/ProductService.java

상품 상세 조회 api 브랜드id로 내려주기
(issue에서는 브랜드명을 브랜드id로 바꾼다고 작성하였는데, admin페이지에서도
사용할 수 있어, 기존 브랜드명은 그대로 두고, 브랜드id를 추가하는 방식 채택)
수정하면서, reviewCount 안내려주고 있는 것도 발견해서 추가하였습니다!
어떤 변경 사항이 있나요?

feat: 상품 상세 조회 api 브랜드id로 내려주기

---

.idea/.gitignore
src/main/java/spharos/msg/domain/options/service/OptionsService.java

기존엔 옵션이 없는 타입의 경우 에러가 발생했는데 이제 빈 배열을 반환합니다.
#172 
어떤 변경 사항이 있나요?

fix : 옵션이 없는 상품의 옵션 타입 조회 시 빈 배열 반환 #172

---

src/main/java/spharos/msg/domain/users/controller/AuthController.java
src/main/java/spharos/msg/domain/users/dto/response/FindUserInfoOutDto.java
src/main/java/spharos/msg/domain/users/service/AuthServiceImpl.java

#180 
api의 요구조건이 변경되어 수정 진행하였습니다.
어떤 변경 사항이 있나요?

want : 회원 정보 조회 API Response Data 추가

---

src/main/java/spharos/msg/domain/brand/controller/BrandController.java
src/main/java/spharos/msg/domain/brand/dto/BrandDetailDto.java
src/main/java/spharos/msg/domain/brand/service/BrandService.java
src/main/java/spharos/msg/global/api/code/status/SuccessStatus.java

브랜드 id를 받아 브랜드 상세 정보를 조회함
#193 
어떤 변경 사항이 있나요?

feat : 브랜드 상세 조회 #193

---

src/main/java/spharos/msg/domain/orders/converter/OrderProductConverter.java
src/main/java/spharos/msg/domain/orders/converter/OrdersConverter.java
src/main/java/spharos/msg/domain/orders/dto/OrderResponse.java
src/main/java/spharos/msg/domain/orders/repository/OrderProductRepository.java
src/main/java/spharos/msg/domain/orders/repository/impl/OrderRepositoryCustomImpl.java
src/main/java/spharos/msg/domain/orders/service/OrderProductService.java
src/main/java/spharos/msg/domain/orders/service/OrderService.java
src/main/java/spharos/msg/domain/product/converter/ProductSalesInfoConverter.java
src/main/java/spharos/msg/domain/review/repository/ReviewRepository.java

Orders 패키지 리팩토링하여 아래 2가지를 리팩토링 했습니다.
#177 를 참고하시면 좋습니다.
1. Converter를 통한 toDto 로직 구현
2. Projection을 @QueryProjection을 사용하여 간략하게 표기
어떤 변경 사항이 있나요?

refactor : Order 패키지 리팩토링 #177

---

src/main/java/spharos/msg/domain/category/converter/CategoryConverter.java
src/main/java/spharos/msg/domain/category/dto/CategoryResponse.java
src/main/java/spharos/msg/domain/category/repository/impl/CategoryProductRepositoryCustomImpl.java
src/main/java/spharos/msg/domain/category/service/CategoryService.java

#179 Category 패키지 코드 리팩토링
어떤 변경 사항이 있나요?

refactor : Category 패키지 코드 리팩토링 #179

---

src/main/java/spharos/msg/domain/search/converter/SearchConverter.java
src/main/java/spharos/msg/domain/search/dto/SearchResponse.java
src/main/java/spharos/msg/domain/search/repository/SearchRepositoryImpl.java
src/main/java/spharos/msg/domain/search/service/SearchService.java

Search 패키지 리팩토링 적용완료
어떤 변경 사항이 있나요?

refactor : Search 패키지 리팩토링 #183

---

src/main/java/spharos/msg/domain/options/controller/OptionsController.java
src/main/java/spharos/msg/domain/options/dto/OptionsNameDto.java
src/main/java/spharos/msg/domain/options/service/OptionsService.java

장바구니에서 옵션 조회를 위한 api 추가 했습니다.
#142 
어떤 변경 사항이 있나요?

feat : 상품 옵션명 조회 #142

---

src/main/java/spharos/msg/domain/users/dto/response/AuthResponse.java
src/main/java/spharos/msg/domain/users/repository/UsersRepository.java
src/main/java/spharos/msg/domain/users/service/impl/AddressServiceImplV2.java
src/main/java/spharos/msg/domain/users/service/impl/AuthServiceImplV2.java
src/main/java/spharos/msg/domain/users/service/impl/OAuthServiceImplV2.java

1. Address Service / Address Create 시, N+1 문제 해결하였습니다.
2. Auth Service / 회원가입 시 Dto Projection 적용하였습니다.
3. Auth Service / 로그인 아이디 찾을 시, Dto Projection 적용하였습니다.
4. Auth Service / 유저 정보 검색 시, Dto Projection 적용하였습니다.
5. OAuth Service / 간편 회원 로그인 시, Dto Projection 적용하였습니다.
특이사항
@Primary 애노테이션을 사용하여 사용할 추상화 되어있는 Service를 컨테이너에 우선순위 등록하게 작성하였습니다.
어떤 변경 사항이 있나요?

perf : Users Domain 성능 최적화

---

src/main/java/spharos/msg/MsgApplication.java
src/main/java/spharos/msg/domain/bundle/controller/BundleController.java
src/main/java/spharos/msg/domain/bundle/convertor/BundleConvertor.java
src/main/java/spharos/msg/domain/bundle/dto/BundleResponse.java
src/main/java/spharos/msg/domain/bundle/service/BundleService.java
src/main/java/spharos/msg/domain/product/service/ProductService.java

번들 id로 특가상품에 대한 정보를 반환하는 api 만들었습니다.
기존에 있던 컨트롤러의 dto 필드를 추가해서 확장하였습니다.
어떤 변경 사항이 있나요?

feat: 번들id로 번들정보 조회 api 구현

---

src/main/java/spharos/msg/domain/admin/controller/CountUserController.java
src/main/java/spharos/msg/domain/admin/converter/AdminConverter.java
src/main/java/spharos/msg/domain/admin/dto/AdminResponseDto.java
src/main/java/spharos/msg/domain/admin/service/CountUserService.java
src/main/java/spharos/msg/domain/admin/service/Impl/CountUserServiceImpl.java
src/main/java/spharos/msg/domain/users/repository/UsersRepository.java
src/main/java/spharos/msg/domain/users/service/impl/AddressServiceImpl.java
src/main/java/spharos/msg/global/api/code/status/SuccessStatus.java

#211 
Admin용 API 하나 추가되었습니다.
내용은 유저 이름으로 유저 정보를 조회하는 API 입니다.
어떤 변경 사항이 있나요?

feat : Admin용 User 검색 기능 구현 #211

---

src/main/java/spharos/msg/global/config/SecurityConfig.java

local 환경 cors 오류로 직접 허용 처리
어떤 변경 사항이 있나요?

fix : localhost:3000 직접 허용 처리

---

src/main/java/spharos/msg/domain/admin/service/CountPriceService.java
src/main/java/spharos/msg/domain/admin/service/Impl/CountUserServiceImplV2.java
src/main/java/spharos/msg/domain/orders/controller/OrderControllerV1.java
src/main/java/spharos/msg/domain/orders/controller/OrderControllerV2.java
src/main/java/spharos/msg/domain/orders/dto/OrderResponse.java
src/main/java/spharos/msg/domain/orders/repository/OrderProductRepository.java
src/main/java/spharos/msg/domain/orders/service/OrderProductService.java
src/main/java/spharos/msg/domain/orders/service/OrderServiceV1.java
src/main/java/spharos/msg/domain/orders/service/OrderServiceV2.java
src/main/java/spharos/msg/domain/search/repository/SearchRepositoryImpl.java
src/main/java/spharos/msg/domain/users/repository/UsersRepository.java
src/main/java/spharos/msg/domain/users/repository/UsersRepositoryQueryDsl.java
src/main/java/spharos/msg/domain/users/repository/UsersRepositoryQueryDslImpl.java
src/test/java/spharos/msg/domain/orders/service/OrderServiceTest.java

성능 최적화를 완료했습니다.
또한 v1과 v2 클래스를 분리하고, API를 분리했습니다.
Jmeter를 통해선 정확한 테스트를 하지못했지만..쿼리문을 통해 1+N 문제가 없는것을 확인했고, 쿼리문이 줄어들었던 것을 확인했습니다.
어떤 변경 사항이 있나요?

refactor : Order API 성능 최적화

---

src/main/java/spharos/msg/domain/users/controller/v1/AddressControllerV1.java
src/main/java/spharos/msg/domain/users/controller/v1/AuthControllerV1.java
src/main/java/spharos/msg/domain/users/controller/v1/OAuthControllerV1.java
src/main/java/spharos/msg/domain/users/controller/v1/UsersControllerV1.java
src/main/java/spharos/msg/domain/users/controller/v2/AddressControllerV2.java
src/main/java/spharos/msg/domain/users/controller/v2/AuthControllerV2.java
src/main/java/spharos/msg/domain/users/controller/v2/OAuthControllerV2.java
src/main/java/spharos/msg/domain/users/controller/v2/UsersControllerV2.java
src/main/java/spharos/msg/domain/users/service/impl/v1/AddressServiceImplV1.java
src/main/java/spharos/msg/domain/users/service/impl/v1/AuthServiceImplV1.java
src/main/java/spharos/msg/domain/users/service/impl/v1/OAuthServiceImplV1.java
src/main/java/spharos/msg/domain/users/service/impl/v1/UsersServiceImplV1.java
src/main/java/spharos/msg/domain/users/service/impl/v2/AddressServiceImplV2.java
src/main/java/spharos/msg/domain/users/service/impl/v2/AuthServiceImplV2.java
src/main/java/spharos/msg/domain/users/service/impl/v2/OAuthServiceImplV2.java
src/main/java/spharos/msg/domain/users/service/impl/v2/UsersServiceImplV2.java
src/main/java/spharos/msg/global/config/SecurityConfig.java

Users Domain의 성능최적화 전/후 버젼을 V1/V2로 구분하여 분기하였습니다.
목적은 동시 테스트를 하기 위함 입니다.
어떤 변경 사항이 있나요?

refactor : Users Api V1, V2 분기

---

src/main/java/spharos/msg/domain/admin/controller/v1/CountUserControllerV1.java
src/main/java/spharos/msg/domain/admin/controller/v2/CountUserControllerV2.java
src/main/java/spharos/msg/domain/admin/converter/AdminConverter.java
src/main/java/spharos/msg/domain/admin/dto/AdminResponseDto.java
src/main/java/spharos/msg/domain/admin/service/Impl/CountUserServiceImplV1.java
src/main/java/spharos/msg/domain/admin/service/Impl/CountUserServiceImplV2.java
src/main/java/spharos/msg/domain/users/repository/UsersRepositoryQueryDsl.java
src/main/java/spharos/msg/domain/users/repository/UsersRepositoryQueryDslImpl.java
src/main/java/spharos/msg/global/config/SecurityConfig.java

#204 
Admin Users 의 API 성능을 최적화 시켰습니다.
1. Spring Data Jpa Pageable -> Query Dsl Jpa Pageable + Projection 적용.
2. Query DSL 사용하여 DB에서 집계 후, 데이터 추출하도록 변경.
두가지 모두 Local 환경에서의 JMeter 성능 테스트 완료하였고, 유의미한 성능 개선이 있었습니다.
따라서 배포 환경에서 테스트 하고자 합니다.
어떤 변경 사항이 있나요?

perf : Admin Users 성능 최적화

---

src/main/java/spharos/msg/domain/brand/controller/BrandControllerV1.java
src/main/java/spharos/msg/domain/brand/controller/BrandControllerV2.java
src/main/java/spharos/msg/domain/brand/dto/BrandDetailDto.java
src/main/java/spharos/msg/domain/brand/dto/BrandResponseDto.java
src/main/java/spharos/msg/domain/brand/repository/BrandRepository.java
src/main/java/spharos/msg/domain/brand/service/BrandServiceV1.java
src/main/java/spharos/msg/domain/brand/service/BrandServiceV2.java

브랜드 api 성능 개선했습니다
#226 
어떤 변경 사항이 있나요?

refactor : 브랜드 관련 api 성능 개선#226

---

src/main/java/spharos/msg/domain/search/controller/SearchControllerV1.java
src/main/java/spharos/msg/domain/search/controller/SearchControllerV2.java
src/main/java/spharos/msg/domain/search/repository/SearchRepository.java
src/main/java/spharos/msg/domain/search/repository/SearchRepositoryImpl.java
src/main/java/spharos/msg/domain/search/service/SearchServiceV1.java
src/main/java/spharos/msg/domain/search/service/SearchServiceV2.java
src/test/java/spharos/msg/domain/search/service/SearchServiceV1Test.java

refactor : Search 관련 API 성능 최적화

---

src/main/java/spharos/msg/domain/category/entity/CategoryProduct.java
src/main/java/spharos/msg/domain/category/repository/impl/CategoryProductRepositoryCustomImpl.java
src/main/java/spharos/msg/domain/product/repository/impl/ProductRepositoryCustomImpl.java
src/main/java/spharos/msg/global/config/SecurityConfig.java

leftJoin을 모두 innerjoin으로 변경하였습니다.
어떤 변경 사항이 있나요?

refactor: 베스트 상품 api와 여러 상품 조회 api 성능 개선
